# Generated by Django 3.2.2 on 2021-05-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
    ]
