# Generated by Django 3.2.2 on 2021-06-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='status',
        ),
    ]
